Revert "Bump spring-boot-starter-parent from 2.7.6 to 3.0.1 (#14)"
This reverts commit b615cbb6ed97840b6ab7c7c3267ffa7a417b196f.

The upgrade caused this error:

java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
    at com.github.mob41.blapi.BLDevice.auth(BLDevice.java:388) ~[broadlink-java-api-1.0.1.jar!/:na]
    at com.github.mob41.blapi.BLDevice.auth(BLDevice.java:366) ~[broadlink-java-api-1.0.1.jar!/:na]
    at de.malkusch.broadlinkBulb.BroadlinkBulb.<init>(BroadlinkBulb.java:24) ~[broadlink-bulb-api-0.2.2.jar!/:na]
    at de.malkusch.broadlinkBulb.BroadlinkBulbFactory.build(BroadlinkBulbFactory.java:134) ~[broadlink-bulb-api-0.2.2.jar!/:na]
    at de.malkusch.broadlinkBulb.BroadlinkBulbFactory.discover(BroadlinkBulbFactory.java:100) ~[broadlink-bulb-api-0.2.2.jar!/:na]
    at de.malkusch.broadlinkBulb.BroadlinkBulbFactory.discover(BroadlinkBulbFactory.java:69) ~[broadlink-bulb-api-0.2.2.jar!/:na]
    at de.malkusch.ha.automation.infrastructure.light.BroadlinkLightRepository.<init>(BroadlinkLightRepository.java:21) ~[classes!/:0.0.1-SNAPSHOT]
    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:na]
    …
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter
    …